name: Deploy to server

on:
  push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: 'value'

    steps:
      - name: Hola mundo
        run: echo "Hola mundo + $NAME"

  second_job:
    if: github.ref == 'refs/heads/B'
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo 2"


