name: Deploy to server

on:
  push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: 'value'

    steps:
      - name: Working directory
        run: ls -al
      - name: Action
        uses: actions/checkout@v2  # Checkout the repository

  second_job:
    if: github.ref == 'refs/heads/B' # Only run this job if the branch is 'B' 
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo 2"


